JEIEvents.hideItems(event => {
    event.hide('tconstruct:efln_ball')
    event.hide('tconstruct:piggy_backpack')
    event.hide('create_enchantment_industry:printer')
    event.hide('minecraft:tnt_minecart')
    event.hide('minecraft:enchanted_golden_apple')
    event.hide('createrailwaysnavigator:navigator')
    event.hide('tconstruct:steel_block')
    event.hide('tconstruct:steel_ingot')
    event.hide('tconstruct:steel_nugget')
    event.hide('create_radar:plane_radar')
    event.hide('dragonlib:dragon')
    event.hide('createbigcannons:partially_assembled_machine_gun_round')
    event.hide('createbigcannons:partially_formed_big_cartrige')
    event.hide('createbigcannons:partially_filled_autocannon_cartrige')
    event.hide('createbigcannons:partially_formed_autocannon_cartrige')
    event.hide('createbigcannons:partial_steel_autocannon_breech_extractor')
    event.hide('createbigcannons:partial_bronze_autocannon_breech_extractor')
    event.hide('createbigcannons:partial_cast_iron_autocannon_breech_extractor')
    event.hide('createbigcannons:partial_recoil_spring')
    event.hide('slotid:souls')
    event.hide('createbigcannons:mortar_stone_projectile')
    event.hide('createbigcannons:yaw_controller')
    event.hide('create_radar:track_controller')
    event.hide('create_radar:id_block')
    event.hide('powergrid:debug')
    event.hide('create_connected:linked_transmitter')

    event.hide('#tconstruct:modifiable')
    event.hide('#kubejs:hammers')

    event.hide('tconstruct:long_fall')
    event.hide('tconstruct:soul_belt')
    event.hide('tconstruct:soulbound')
    event.hide('tconstruct:autosmelt')
    event.hide('tconstruct:flinging')
    event.hide('tconstruct:warping')
    event.hide('tconstruct:wings')
    event.hide('tconstruct:unbreakable')

    event.hide('createcasing:vertical_refined_radiance_gearbox')
    event.hide('createcasing:refined_radiance_gearbox')
    event.hide('createcasing:refined_radiance_mixer')
    event.hide('createcasing:refined_radiance_press')
    event.hide('createcasing:refined_radiance_depot')
    event.hide('createcasing:refined_radiance_encased_chain_drive')
    event.hide('createcasing:refined_radiance_adjustable_chain_gearshift')
    event.hide('createcasing:refined_radiance_configurable_gearbox')
    event.hide('createcasing:refined_radiance_chain_conveyor')
    

    event.hide('createcasing:vertical_shadow_steel_gearbox')
    event.hide('createcasing:shadow_steel_gearbox')
    event.hide('createcasing:shadow_steel_mixer')
    event.hide('createcasing:shadow_steel_press')
    event.hide('createcasing:shadow_steel_depot')
    event.hide('createcasing:shadow_steel_encased_chain_drive')
    event.hide('createcasing:shadow_steel_adjustable_chain_gearshift')
    event.hide('createcasing:shadow_steel_configurable_gearbox')
    event.hide('createcasing:shadow_steel_chain_conveyor')
    event.hide('createcasing:vertical_shadow_steel_gearbox')
    event.hide('createcasing:shadow_steel_gearbox')

    event.hide('createcasing:refined_radiance_encased_chain_drive')
    event.hide('createcasing:refined_radiance_gearbox')
    event.hide('createcasing:vertical_refined_radiance_gearbox')

    event.hide('create_enchantment_industry:hyper_experience_bottle')

    function colorhide(coloredInput) {
        event.hide(coloredInput)
    }

    colorhide('minecraft:white_concrete_powder')
    colorhide('minecraft:orange_concrete_powder')
    colorhide('minecraft:magenta_concrete_powder')
    colorhide('minecraft:light_blue_concrete_powder')
    colorhide('minecraft:yellow_concrete_powder')
    colorhide('minecraft:lime_concrete_powder')
    colorhide('minecraft:pink_concrete_powder')
    colorhide('minecraft:gray_concrete_powder')
    colorhide('minecraft:light_gray_concrete_powder')
    colorhide('minecraft:cyan_concrete_powder')
    colorhide('minecraft:purple_concrete_powder')
    colorhide('minecraft:blue_concrete_powder')
    colorhide('minecraft:brown_concrete_powder')
    colorhide('minecraft:green_concrete_powder')
    colorhide('minecraft:red_concrete_powder')
    colorhide('minecraft:black_concrete_powder')

    colorhide('minecraft:white_concrete')
    colorhide('minecraft:orange_concrete')
    colorhide('minecraft:magenta_concrete')
    colorhide('minecraft:light_blue_concrete')
    colorhide('minecraft:yellow_concrete')
    colorhide('minecraft:lime_concrete')
    colorhide('minecraft:pink_concrete')
    colorhide('minecraft:gray_concrete')
    colorhide('minecraft:light_gray_concrete')
    colorhide('minecraft:cyan_concrete')
    colorhide('minecraft:purple_concrete')
    colorhide('minecraft:blue_concrete')
    colorhide('minecraft:brown_concrete')
    colorhide('minecraft:green_concrete')
    colorhide('minecraft:red_concrete')
    colorhide('minecraft:black_concrete')

    event.hide('railways:white_imcomplete_conductor_cap')
    event.hide('railways:orange_imcomplete_conductor_cap')
    event.hide('railways:magenta_imcomplete_conductor_cap')
    event.hide('railways:light_blue_imcomplete_conductor_cap')
    event.hide('railways:yellow_imcomplete_conductor_cap')
    event.hide('railways:lime_imcomplete_conductor_cap')
    event.hide('railways:pink_imcomplete_conductor_cap')
    event.hide('railways:gray_imcomplete_conductor_cap')
    event.hide('railways:light_gray_imcomplete_conductor_cap')
    event.hide('railways:cyan_imcomplete_conductor_cap')
    event.hide('railways:purple_imcomplete_conductor_cap')
    event.hide('railways:blue_imcomplete_conductor_cap')
    event.hide('railways:brown_imcomplete_conductor_cap')
    event.hide('railways:green_imcomplete_conductor_cap')
    event.hide('railways:red_imcomplete_conductor_cap')
    event.hide('railways:black_imcomplete_conductor_cap')

    event.hide('railways:track_incomplete_create_andesite_wide')
    event.hide('railways:track_incomplete_create_andesite_narrow')
    event.hide('railways:track_incomplete_monorail')

    event.hide('createaddition:electrum_block')
    event.hide('createdieselgenerators:wire_cutters')
    event.hide('createaddition:alternator')
    event.hide('createdeco:zinc_sheet')
    event.hide('createaddition:zinc_sheet')
    event.hide('electrical_connector')
    event.hide('createaddition:zinc_sheet')
    event.hide('create_new_age:copper_wire')
    event.hide('create_new_age:overcharged_iron_wire')
    event.hide('create_new_age:overcharged_golden_wire')
    event.hide('create_new_age:diamond_wire')
    event.hide('create_new_age:energiser_t1')
    event.hide('create_new_age:energiser_t2')
    event.hide('create_new_age:energiser_t3')
    event.hide('create_new_age:overcharged_iron')
    event.hide('create_new_age:overcharged_gold')
    event.hide('create_new_age:overcharged_iron_sheet')
    event.hide('create_new_age:overcharged_golden_sheet')
    
    


    event.hide('tconstruct:tools/modifiers/ability/soul_belt')
    event.hide('tconstruct:tools/modifiers/upgrade/soulbound')
    event.hide('tconstruct:tools/modifiers/ability/autosmelt')
    event.hide('tconstruct:tools/modifiers/ability/flinging')
    event.hide('tconstruct:tools/modifiers/ability/wings')
    event.hide('tconstruct:tools/modifiers/ability/unbreakable')
    event.hide('tconstruct:tools/modifiers/ability/long_fall')


})